package karega.scott.alright.models;

public enum AlrightStateType {
		WARNING,
		ERROR,
		SETUP_GAME,
		NO_CHANGE,
		MY_LOCATION,
		DESTINATION_CHANGED,
		GAME_STARTED,
		GAME_SETUP_COMPLETE,
		STILL_ON_TRACK,
		GAME_OVER_LOSER,
		GAME_OVER_WINNER,
		CONNECTED,
		DISCONNECTED,
}
